spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/los_santos_custom
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      defer-datasource-initialization: true
    show-sql: true
